---
title: "Spotify Genre Analysis"
author: "Maxime St-Jean"
date: "`r Sys.Date()`"
output: html_document
---

```{r user-determined variables, echo = F}
## Variables to change:

csv_filename = "spotify_past_year_wgenres.csv"
time_zone    =  "America/New_York"
```

```{r packages and data loading, echo = F, warning = F, message = F}
library(tidyverse)
library(lubridate)

df = read_csv(csv_filename)
```

```{r recodes and variables, echo = F, warning = F, message=F}
# adds a column of hour in local time
df$tz_hour = hour(with_tz(df$ts, time_zone))

# Vector of genres in the dataset
genre_cols = colnames(df)[21:length(colnames(df))-1]

pms = paste(seq(1:11), "pm", sep = "")
ams = paste(seq(1:11), "am", sep = "")

time_levels = c("12am", ams, "12pm", pms)
```

```{r song plays frequency table, echo = F, warning = F, message=F}
# taking most frequent genres (by song plays)
genre_counts = df %>%
  summarise(across(all_of(genre_cols), sum)) %>% 
  pivot_longer(everything(), names_to = "genre", values_to = "ms") %>% 
  arrange(desc(ms)) %>% mutate(percent = ms/sum(ms) * 100)

# here I only take the top 5 genres, this can be as many as you want however
analysis_cols = genre_counts$genre[1:5]

freq_table = df %>%
  group_by(tz_hour) %>%
  summarise(across(all_of(analysis_cols), sum)) %>% 
  pivot_longer(all_of(analysis_cols),
               names_to = "Genre",
               values_to = "count") %>% 
  mutate(tz_hour = factor(tz_hour,
                          levels = c(4:23, 0:3),
                          labels = c(time_levels[5:24], time_levels[1:4]))) %>%
  ungroup()
```

```{r song plays graph, echo = F, warning = F, message = F}
ggplot(freq_table, aes(x = tz_hour, y = count, group = Genre, color = Genre))+
  geom_line() +
  scale_x_discrete(breaks = c("6am", "12pm", "6pm", "12am"),
                   labels = c("6am", "12pm", "6pm", "12am")) +
  coord_cartesian(ylim = c(0, 1500)) +
  labs(x = "Hour of the day",
       y = "Number of song plays",
       title = "Genre by song plays")
```

```{r time played freq table, echo = F, message=F}
## Here we have the same process as above, but by time played rather than
#  song plays

genre_counts = df %>%
  summarise(across(all_of(genre_cols), ~ sum(.x * ms_played))) %>% 
  pivot_longer(everything(), names_to = "genre", values_to = "ms") %>% 
  arrange(desc(ms)) %>% mutate(percent = ms/sum(ms) * 100)

analysis_cols = genre_counts$genre[1:5]

freq_table = df %>%
  group_by(tz_hour) %>%
  summarise(across(all_of(analysis_cols),
                   ~ sum(.x * (ms_played / 60000)))) %>% 
  pivot_longer(all_of(analysis_cols),
               names_to = "Genre",
               values_to = "count") %>%
  mutate(tz_hour = factor(tz_hour,
                           levels = c(4:23, 0:3),
                           labels = c(time_levels[5:24], time_levels[1:4]))) %>%
  ungroup()
```

```{r time played graph, echo = F}
ggplot(freq_table, aes(x = tz_hour, y = count, group = Genre, color = Genre)) +
  geom_line() +
#  stat_smooth(se = F) +
  scale_x_discrete(breaks = c("6am", "12pm", "6pm", "12am"),
                   labels = c("6am", "12pm", "6pm", "12am")) +
  labs(x = "Hour of the day",
       y = "Minutes of play",
       title = "Genre by listening time")
```


